#!/bin/bash
#echo schedutil | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
#echo 4785000 | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_max_freq 
#echo 4785000 | tee /sys/devices/system/cpu/cpu*/cpufreq/amd_pstate_max_freq

echo active > /sys/devices/system/cpu/amd_pstate/status
echo power | tee /sys/devices/system/cpu/cpufreq/policy*/energy_performance_preference